package com.jinjoo.pouch.api.model.pub

data class Item (
    var ITEM_NAME: String = "",
    var COSMETIC_REPORT_SEQ: String = "",
    var ITEM_SEQ: String = "",
    var DEPT_RECEIPT_NO: String = "",
    var REPORT_FLAG_CODE: String = "",
    var REPORT_FLAG_NAME: String = "",
    var MANUF_NAME: String = "",
    var MANUF_COUNTRY_CODE: String = "",
    var MANUF_COUNTRY_NAME: String = "",
    var MANUF_PLACE: String = "",
    var ITEM_PH: String = "",
    var COSMETIC_TARGET_FLAG: String = "",
    var COSMETIC_TARGET_FLAG_NAME: String = "",
    var COSMETIC_STD_CODE: String = "",
    var COSMETIC_STD_NAME: String = "",
    var ENTP_NAME: String = "",
    var ENTP_SEQ: String = "",
    var REPORT_DATE: String = "",
    var CANCEL_REQ_DATE: String = "",
    var CANCEL_APPROVAL_DATE: String = "",
    var CANCEL_APPROVAL_YN: String = "",
    var ETHANOL_OVER_YN: String = "",
    var EE_CODE: String = "",
    var EE_NAME: String = "",
    var SPF: String = "",
    var PA: String = "",
    var USAGE_DOSAGE: String = "",
    var EFFECT_YN1: String = "",
    var EFFECT_YN2: String = "",
    var EFFECT_YN3: String = "",
    var WATER_PROOFING_FLAG: String = "",
    var WATER_PROOFING_NAME: String = "",
    var EE_DOC_DATA: String = "",
    var UD_DOC_DATA: String = "",
    var NB_DOC_DATA: String = ""
)