package com.jinjoo.pouch.api.model.pub

data class Item (
    var ITEM_NAME: String? = null,
    var COSMETIC_REPORT_SEQ: String? = null,
    var ITEM_SEQ: String? = null,
    var DEPT_RECEIPT_NO: String? = null,
    var REPORT_FLAG_CODE: String? = null,
    var REPORT_FLAG_NAME: String? = null,
    var MANUF_NAME: String? = null,
    var MANUF_COUNTRY_CODE: String? = null,
    var MANUF_COUNTRY_NAME: String? = null,
    var MANUF_PLACE: String? = null,
    var ITEM_PH: String? = null,
    var COSMETIC_TARGET_FLAG: String? = null,
    var COSMETIC_TARGET_FLAG_NAME: String? = null,
    var COSMETIC_STD_CODE: String? = null,
    var COSMETIC_STD_NAME: String? = null,
    var ENTP_NAME: String? = null,
    var ENTP_SEQ: String? = null,
    var REPORT_DATE: String? = null,
    var CANCEL_REQ_DATE: String? = null,
    var CANCEL_APPROVAL_DATE: String? = null,
    var CANCEL_APPROVAL_YN: String? = null,
    var ETHANOL_OVER_YN: String? = null,
    var EE_CODE: String? = null,
    var EE_NAME: String? = null,
    var SPF: String? = null,
    var PA: String? = null,
    var USAGE_DOSAGE: String? = null,
    var EFFECT_YN1: String? = null,
    var EFFECT_YN2: String? = null,
    var EFFECT_YN3: String? = null,
    var WATER_PROOFING_FLAG: String? = null,
    var WATER_PROOFING_NAME: String? = null,
    var EE_DOC_DATA: String? = null,
    var UD_DOC_DATA: String? = null,
    var NB_DOC_DATA: String? = null
)